### ISSUE TITLE
Issue with get_external_id (odoo 12)

### ISSUE THREAD

**Issue by pedroslopez** [katyukha/odoo-rpc-client#7]
Hi! When using the `get_external_id` method for a record, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\Administrador\Desktop\odoo_payroll_xml_export_XMLIDS.py", line 25, in <module>
    data_external_id = data.get_external_id()
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\odoo_rpc_client\orm\object.py", line 102, in wrapper
    **kwargs)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\odoo_rpc_client\service\object.py", line 44, in execute
    kwargs)
odoo_rpc_client.connection.xmlrpc.XMLRPCError: b'A fault occured\nFault code: dictionary key must be string\nFault string: Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 54, in xmlrpc_1\n    response = self._xmlrpc(service)\n  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 44, in _xmlrpc\n    return dumps((result,), methodresponse=1, allow_none=False)\n  File "/usr/lib/python3.5/xmlrpc/client.py", line 951, in dumps\n    data = m.dumps(params)\n  File "/usr/lib/python3.5/xmlrpc/client.py", line 501, in dumps\n    dump(v, write)\n  File "/usr/lib/python3.5/xmlrpc/client.py", line 523, in __dump\n    f(self, value, write)\n  File "/usr/lib/python3.5/xmlrpc/client.py", line 592, in dump_struct\n    raise TypeError("dictionary key must be string")\nTypeError: dictionary key must be string\n\n
```

Python 3.5, Odoo 12

Thanks!

**Comment by katyukha** [comment]
Hi!

Thanks for reporting this issue.

It seems that this bug is result of limitations of xmlrpc.

Try to use json-rpc protocol.

**Comment by katyukha** [comment]
No activity for 1 year. Closing
